FROM python:3.10-slim

WORKDIR /app

COPY api/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/
COPY model/ ./model/

WORKDIR /app/api

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]